### ISSUE TITLE
Considering pointing to canonical MIT license to allow license validation check to pass

### ISSUE THREAD

**Issue by jrodbx** [underdog-tech/pinwheel-android-sdk#42]
We have a Gradle plugin that validates the licenses used in our dependency graph: https://github.com/cashapp/licensee

And using this SDK triggers the following failure:
```
> Task :app:licenseeInternalDebug FAILED
com.getpinwheel:pinwheel-android:2.3.5
 - ERROR: Unknown license URL 'https://github.com/underdog-tech/pinwheel-android-sdk/blob/main/LICENSE' is NOT allowed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:licenseeInternalDebug'.
> Artifacts failed validation. See output above.
```

According to these related issues,
https://github.com/airbnb/lottie-android/issues/527
https://github.com/square/kotlinpoet/issues/1077

it appears to be because the POM points to a custom license file/URL: https://search.maven.org/artifact/com.getpinwheel/pinwheel-android/2.3.5/aar

Here's an example of a POM that uses the suggested template: https://search.maven.org/artifact/com.squareup/kotlinpoet/1.8.0/jar

More info here:
https://maven.apache.org/pom.html#Licenses
https://spdx.org/licenses/MIT.html

**Comment by rawbee** [comment]
@jrodbx release 2.3.6 has the updated license fields. Thanks for calling it out, and please let me know if anything else comes up.
